### ISSUE TITLE
Problem to use rs dedupe

### ISSUE THREAD

**Issue by DaielChom** [mapbox/robosat#106]
Good morning. when i use dedupe funtion the process is interrupted
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daielchom/Documents/Proyectos/Trabajo/ALL_MODEL_OUTPUT_02/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/home/daielchom/Documents/Proyectos/Trabajo/ALL_MODEL_OUTPUT_02/robosat/robosat/tools/dedupe.py", line 63, in main
    if iou(predicted_shape, intersecting_shapes) < args.threshold:
  File "/home/daielchom/Documents/Proyectos/Trabajo/ALL_MODEL_OUTPUT_02/robosat/robosat/spatial/core.py", line 59, in iou
    intersection = lhs.intersection(rhs)
  File "/home/daielchom/Documents/Proyectos/Trabajo/venv/lib/python3.6/site-packages/shapely/geometry/base.py", line 620, in intersection
    return geom_factory(self.impl['intersection'](self, other))
  File "/home/daielchom/Documents/Proyectos/Trabajo/venv/lib/python3.6/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/home/daielchom/Documents/Proyectos/Trabajo/venv/lib/python3.6/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7fa75d768978>

```

**Comment by daniel-j-h** [comment]
Do you have an example GeoJSON we can use for debugging? Or the specific geometry where it fails?

**Comment by DaielChom** [comment]
I can solve the problem, the Ground truth file you were using had several invalid polygons. thank you very much

**Comment by daniel-j-h** [comment]
Great! Quick question: did you use `rs extract` to generate this file with the invalid polygons? Or did you get the polygon file externally through other means?

**Comment by DaielChom** [comment]
I used a geojson GT file external to robosat.

**Comment by daniel-j-h** [comment]
:+1:
