### ISSUE TITLE
ConnectionRefusedError on second training epoch

### ISSUE THREAD

**Issue by wboykinm** [mapbox/robosat#126]
On completion of a single training epoch [using this workflow](https://gist.github.com/wboykinm/38a0e9e99a2c51c3a021f5abf08b0736), `./rs train` throws the following error:

```
root@f5a70d76856f:/app# ./rs train --model config/model-unet-rutland.toml --dataset config/dataset-building.toml 
--- Hyper Parameters on Dataset: rutland/ ---
Batch Size:	 1
Image Size:	 256
Learning Rate:	 0.0001
Weight Decay:	 0.0001
Loss function:	 CrossEntropy
Weights :	 [1.481308, 13.684548]
---
Epoch: 1/2
Train: 100%|##################################################################################################################################| 127/127 [15:39<00:00,  7.40s/batch]
Train    loss: 0.5145, mIoU: 0.507, building IoU: 0.081, MCC: 0.140
Validate: 100%|#################################################################################################################################| 14/14 [00:22<00:00,  1.60s/batch]
Validate loss: 0.3873, mIoU: 0.475, building IoU: 0.141, MCC: 0.313
Epoch: 2/2
Train:   1%|#                                                                                                                                   | 1/127 [00:10<22:52, 10.90s/batch]Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f9d62863e80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/robosat/tools/__main__.py", line 60, in <module>
    args.func(args)
  File "/app/robosat/tools/train.py", line 133, in main
    train_hist = train(train_loader, num_classes, device, net, optimizer, criterion)
  File "/app/robosat/tools/train.py", line 184, in train
    outputs = net(images)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 109, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/robosat/unet.py", line 139, in forward
    dec5 = self.dec5(dec4)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/robosat/unet.py", line 44, in forward
    return nn.functional.relu(self.block(x), inplace=True)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3212) is killed by signal: Killed.
```

This looks suspiciously like [a pytorch problem experienced by some other folks](https://github.com/amdegroot/ssd.pytorch/issues/163), and in particular this looks like [it may be related to the fact that I'm running this locally on CPU](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/51#issuecomment-315347376).

If the CPU thing is the problem, is there a pipeline'd way for me to tune the number of threads down to 0 per the recommendation in the linked ticket? `batch_size` does not appear to be it.

**Comment by wboykinm** [comment]
[Per @ocourtin](https://gist.github.com/wboykinm/fca0ff96969ddaf3e2b17dad36727491#gistcomment-2726960), this is resolved (on my appallingly-single-cored docker setup) by adding `--workers 0` to the `./rs train` invocation.

**Comment by daniel-j-h** [comment]
I think we should make `worker=0` the default.

I ran into similar worker problems when I was on a box with very little shared memory by default. The workers communicate via shared memory and are getting killed if they can not allocate enough shm.

Workaround was to increase shared memory e.g. via

```
umount /dev/shm
mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=4G shm /dev/shm

# df -h | grep shm
shm  4.0G  0  4.0G   0% /dev/shm
```

**Comment by wboykinm** [comment]
@ocourtin looks like 2 cpus 🤷‍♂️ 

```
>>> import multiprocessing
>>> print(multiprocessing.cpu_count())
2
```
