### ISSUE TITLE
Ignore .DS_Store from the dataset directory

### ISSUE THREAD

**Issue by maning** [mapbox/robosat#47]
Running the stack locally on a mac, the dataset directory will have the`.DS_Store` file which throws an error during `rs train`.

```
./rs train --model config/model-unet.toml --dataset config/dataset-building.toml
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/maning/projects/git/robosat/robosat/tools/__main__.py", line 42, in <module>
    args.func(args)
  File "/Users/maning/projects/git/robosat/robosat/tools/train.py", line 85, in main
    train_loader, val_loader = get_dataset_loaders(model, dataset)
  File "/Users/maning/projects/git/robosat/robosat/tools/train.py", line 218, in get_dataset_loaders
    target_transform)
  File "/Users/maning/projects/git/robosat/robosat/datasets.py", line 55, in __init__
    self.inputs = [SlippyMapTiles(inp, fn) for inp, fn in zip(inputs, input_transforms)]
  File "/Users/maning/projects/git/robosat/robosat/datasets.py", line 55, in <listcomp>
    self.inputs = [SlippyMapTiles(inp, fn) for inp, fn in zip(inputs, input_transforms)]
  File "/Users/maning/projects/git/robosat/robosat/datasets.py", line 26, in __init__
    self.tiles = [(tile, path) for tile, path in tiles_from_slippy_map(root)]
  File "/Users/maning/projects/git/robosat/robosat/datasets.py", line 26, in <listcomp>
    self.tiles = [(tile, path) for tile, path in tiles_from_slippy_map(root)]
  File "/Users/maning/projects/git/robosat/robosat/tiles.py", line 77, in tiles_from_slippy_map
    for name in os.listdir(os.path.join(root, z, x)):
NotADirectoryError: [Errno 20] Not a directory: 'dataset/validation/images/21/.DS_Store'
```

**Comment by daniel-j-h** [comment]
Here's the function responsible for returning tile ids and paths to the images from a slippy map directory:

https://github.com/mapbox/robosat/blob/8d9bd9cbf1edde83f531d267072b6dcb3ba93860/robosat/tiles.py#L65-L81

There we can skip everything not following the `z/x/y.ext` scheme (where ext can e.g. be webp).

**Comment by bkowshik** [comment]
I have had these issues myself and my solution has always been to delete these files manually, yes one after another. But, looking at this ticket made me think, there should be a command to delete all the `.DS_Store` files recursively from the directory.

From [here](https://medium.com/@danilosapad/how-to-recursively-remove-ds-store-files-on-mac-os-x-6c8570c68ad0), I found the following command which worked beautifully, posting for reference:

```bash
find . -name "*.DS_Store" -type f -delete
```

**Comment by AnushSomasundaram** [comment]
> I have had these issues myself and my solution has always been to delete these files manually, yes one after another. But, looking at this ticket made me think, there should be a command to delete all the `.DS_Store` files recursively from the directory.
> 
> From [here](https://medium.com/@danilosapad/how-to-recursively-remove-ds-store-files-on-mac-os-x-6c8570c68ad0), I found the following command which worked beautifully, posting for reference:
> 
> ```shell
> find . -name "*.DS_Store" -type f -delete
> ```

thank you, ive been scratching my head over this for a day now :>
