### ISSUE TITLE
Errors in `rs extract` when extracting .osm.pbf

### ISSUE THREAD

**Issue by toren77** [mapbox/robosat#69]
1.Download Leipzig.osm.pbf from https://download.bbbike.org/osm/bbbike/Leipzig/
2.Run `./rs extract --type building Leipzig.osm.pbf  /data/extracted/`
3.Getting error:

 Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/unexpected/robosat/robosat/tools/__main__.py", line 55, in <module>
    args.func(args)
  File "/home/unexpected/robosat/robosat/tools/extract.py", line 27, in main
    handler.apply_file(filename=args.map, locations=True)
  File "/home/unexpected/robosat/robosat/osm/building.py", line 32, in way
    shape = shapely.geometry.shape(geometry)
  File "/home/unexpected/.local/lib/python3.6/site-packages/shapely/geometry/geo.py", line 35, in shape
    return Polygon(ob["coordinates"][0], ob["coordinates"][1:])
  File "/home/unexpected/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/home/unexpected/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 321, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by daniel-j-h** [comment]
Looks like this is coming from https://github.com/mapbox/robosat/blob/1e687552fe9b254a14d55d2825e8911bb812c63e/robosat/osm/building.py#L21-L38

where we check if the way is closed and if the way has building tags. It looks like the way being closed does not imply three or more coordinates. From my understanding this can only happen in case the data is broken: a closed way with only two nodes, and both nodes are the same.

I can add checks so that we ignore these data issues, thanks for flagging!

**Comment by daniel-j-h** [comment]
It looks like there are ways in your pbf with a single node as its start and end. Here are some:

https://www.openstreetmap.org/way/4981268
https://www.openstreetmap.org/way/5309991
https://www.openstreetmap.org/way/6166982
https://www.openstreetmap.org/way/7355016
https://www.openstreetmap.org/way/19544226

Looking at the data in OpenStreetMap it's fine. It looks like this issue is coming from the way the Leipzig pbf was cut out. I strongly recommend using https://github.com/osmcode/osmium-tool and especially http://docs.osmcode.org/osmium/latest/osmium-extract.html It comes with various strategies how to handle ways crossing the borders; the default strategy already does the right thing.

**Comment by daniel-j-h** [comment]
@toren77 https://github.com/mapbox/robosat/pull/70 should fix your issue.
