### ISSUE TITLE
training is unhappy with uneven number of inputs and target

### ISSUE THREAD

**Issue by CraigglesO** [mapbox/robosat#73]
```
 % ./rs train --model ./config/model-unet.toml --dataset ./config/dataset-building.toml
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/connor/Documents/Regia/building-ccn/robosat-master/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/home/connor/Documents/Regia/building-ccn/robosat-master/robosat/tools/train.py", line 74, in main
    train_loader, val_loader = get_dataset_loaders(model, dataset)
  File "/home/connor/Documents/Regia/building-ccn/robosat-master/robosat/tools/train.py", line 199, in get_dataset_loaders
    [os.path.join(path, "training", "images")], os.path.join(path, "training", "labels"), transform
  File "/home/connor/Documents/Regia/building-ccn/robosat-master/robosat/datasets.py", line 58, in __init__
    assert len(self.target) == len(self.inputs[0]), "same number of tiles in inputs and target"
AssertionError: same number of tiles in inputs and target
```

I followed the guide to the letter. I ensure 19 zoom throughout. I create the dataset with 80% training and 20% validation.

Here is how I subset both images and rasters (masks):
`./rs subset ../download-utah ../training.csv ../dataset/training/images`
`./rs subset ../raster-images ../training.csv ../dataset/training/labels`

Do you have any suggestions on what I should tweak?

Thanks,
Craig.

**Comment by CraigglesO** [comment]
Never-mind.

I wrote a gist that finds all the differences between the images and labels folders. Interesting that this happens.

[GIST HERE](https://gist.github.com/CraigglesO/c96a33ad0e3e26886bb113193c80c607)

Would be easy to have the file also delete the differences. Next iteration I guess. Anyways, for anyone else having this problem, basically the two folders have to be identical.
