### ISSUE TITLE
ImportError: No module named 'mercantile'

### ISSUE THREAD

**Issue by mcavdar** [mapbox/robosat#83]
Hi, I use `pip install -r deps/requirements-lock.txt` for dependencies.

When I run `./rs --help`, I got an error with importing mercantile module:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mc/github/robosat/robosat/tools/__main__.py", line 5, in <module>
    from robosat.tools import (
  File "/home/mc/github/robosat/robosat/tools/compare.py", line 8, in <module>
    from robosat.tiles import tiles_from_slippy_map
  File "/home/mc/github/robosat/robosat/tiles.py", line 16, in <module>
    import mercantile
ImportError: No module named 'mercantile'
```
Problem will be resolved if we use `pip3 install`  instead of `pip install`.

**Comment by mcavdar** [comment]
Even better: `sudo pip3 install ...`

**Comment by daniel-j-h** [comment]
We are using Python3 for this project. It looks like your `pip` command defaults to using Python2.

Also I can not recommend using sudo for installation; install as user or use a virtualenv https://github.com/mapbox/robosat/issues/82.
