### ISSUE TITLE
Error "same number of tiles in inputs and target"

### ISSUE THREAD

**Issue by toren77** [mapbox/robosat#91]
robosat$ ./rs train --model config/model-unet.toml --dataset config/dataset-buildings-dar-es-salam.toml

len(inputs)= 60859
len(inputs[0].tiles)= 60859
target.tiles[0]= (Tile(x=638131, y=543981, z=20), 'data/dar-es-salam-buldings-dataset/training/labels/20/638131/543981.png')
len(target)= 60859

len(inputs)= 7798
len(inputs[0].tiles)= 7798
target.tiles[0]= (Tile(x=638131, y=544010, z=20), 'data/dar-es-salam-buldings-dataset/validation/labels/20/638131/544010.png')
len(target)= 8453

Traceback (most recent call last):
  File "/anaconda3/envs/robosat/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/robosat/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/robosat/robosat/tools/train.py", line 73, in main
    train_loader, val_loader = get_dataset_loaders(model, dataset)
  File "/robosat/robosat/tools/train.py", line 201, in get_dataset_loaders
    [os.path.join(path, "validation", "images")], os.path.join(path, "validation", "labels"), transform
  File "/robosat/robosat/datasets.py", line 62, in __init__
    assert len(self.target) == len(self.inputs[0]), "same number of tiles in inputs and target"
AssertionError: same number of tiles in inputs and target

**Comment by daniel-j-h** [comment]
The number of tiles in your slippy map directory with images has to be the same number of tiles with corresponding masks. This has to hold for both the training as well as validation dataset.

Quick check e.g. via

    find dataset/training/images -type f | wc -l
    find dataset/training/labels -type f | wc -l
