### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by bkowshik** [mapbox/robosat#99]
On the `master` branch, I am running the `rs predict` step which is failing with the following error:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/app/robosat/robosat/tools/predict.py", line 82, in main
    outputs = net(images)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/robosat/robosat/unet.py", line 132, in forward
    dec0 = self.dec0(torch.cat([enc4, center], dim=1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 17 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:111
```

**Comment by bkowshik** [comment]
Thank you for the explanation here @daniel-j-h Things work with `batch_size=32`

- Ref: https://github.com/mapbox/robosat/pull/46#issuecomment-401274775
